version: 2
jobs:
  build:
    working_directory: ~/amio-sdk-js

    docker:
      - image: circleci/node:8.11.1

    steps:
      - checkout

      # Install & Cache Dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-
      - run: npm install
      - save_cache:
                paths:
                  - node_modules
                key: v2-dependencies-{{ checksum "package.json" }}

      - run:
          name: Tests
          command: npm run-script test

workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          context: ctx-amio-sdk-js
